export interface NewsPost {
  id: number;
  title: string;
  notificationtitle: string;
  imagetitel: string;
  content: string;
  created: string;
  postName: string;
  totalLikes: number;
  totalViews: number;
  totalComments: number;
  imageUrl: string;
  videoUrl: string;
  videoPlatform: string;
  gallery: string[];
  type: string;
  totalShares: number;
  isReporter: boolean;
  reportedBy: string;
  categoryName: string[];
  postUrl: string;
  subType: string;
  isStickyPost: boolean;
  linkURLAndroid: string;
  linkURLIos: string;
  links: string | string[];
  bulletPoints?: string[];
  isBookmarked: string[];
  postOrder: number;
  draft: boolean;
  trash: boolean;
  schedule: string;
  languageId?: number;
  categoryIds?: number[];
  locationIds?: number[];
  aitagIds?: number[];
  postType?: string;
  isSticky?: boolean;
  isWebPost?: boolean;
  is_web_post?: boolean;
  web_post_url?: string;
  createdAt?: string;
  updatedAt?: string;
}

